
# Google Cloud Run service definition
# Replace placeholders like YOUR_PROJECT_ID, YOUR_SERVICE_NAME, YOUR_REGION, and YOUR_IMAGE_NAME_TAG

apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: coffeespot-booking # Service name, matches SERVICE_NAME env var in workflow
  annotations:
    run.googleapis.com/launch-stage: BETA
  labels:
    cloud.googleapis.com/location: us-central1 # Matches GAR_LOCATION
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/minScale: '0' # Set to '1' or more for no cold starts
        autoscaling.knative.dev/maxScale: '2' # Adjust as needed
    spec:
      containerConcurrency: 80 # Adjust based on your app's performance
      timeoutSeconds: 300 # Adjust as needed
      containers:
        - image: us-central1-docker.pkg.dev/coffeespot-booking/coffeespot-booking-repo/coffeespot-booking-app:latest # Specific image path
          ports:
            - name: http1
              containerPort: 3000 # Port your Next.js app runs on inside the container (defined in Dockerfile)
          resources:
            limits:
              cpu: 1000m
              memory: 512Mi # Adjust based on your app's needs
          startupProbe:
            timeoutSeconds: 240
            periodSeconds: 240
            failureThreshold: 1
            tcpSocket:
              port: 3000
          env:
            - name: PORT
              value: "3000"
            - name: NODE_ENV
              value: "production"
            # Add any other environment variables your application needs
            # Example:
            # - name: API_KEY
            #   valueFrom:
            #     secretKeyRef:
            #       name: my-api-key-secret # Name of the secret in Google Secret Manager
            #       key: latest # Version of the secret
  traffic:
    - percent: 100
      latestRevision: true

