
name: Build and Deploy to Google Cloud Run

on:
  push:
    branches:
      - main

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }} # User: Ensure this secret is 'coffeespot-booking'
  GAR_LOCATION: us-central1 # Google Cloud region for Artifact Registry and Cloud Run
  SERVICE_NAME: coffeespot-booking-service # Name of your Cloud Run service
  ARTIFACT_REGISTRY_REPO: coffeespot-booking-repo # Name of your Artifact Registry repository
  IMAGE_NAME: coffeespot-booking-app # Name of your Docker image

jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write' # Required for Workload Identity Federation

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Google Auth
        id: auth
        uses: 'google-github-actions/auth@v2'
        with:
          workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }} # User: Ensure this secret points to your new WIF provider (e.g., projects/182184842256/locations/global/workloadIdentityPools/github-actions-pool/providers/YOUR_OIDC_PROVIDER_ID)
          service_account: ${{ secrets.GCP_SERVICE_ACCOUNT }} # User: Ensure this secret is the email of the SA in project 182184842256
          audience: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }} # Explicitly set audience

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Configure Docker
        run: gcloud auth configure-docker ${{ env.GAR_LOCATION }}-docker.pkg.dev --quiet

      - name: Build Docker image
        run: |
          docker build -t ${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.ARTIFACT_REGISTRY_REPO }}/${{ env.IMAGE_NAME }}:${{ github.sha }} \
                       -t ${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.ARTIFACT_REGISTRY_REPO }}/${{ env.IMAGE_NAME }}:latest .

      - name: Push Docker image to Artifact Registry
        run: |
          docker push ${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.ARTIFACT_REGISTRY_REPO }}/${{ env.IMAGE_NAME }}:${{ github.sha }}
          docker push ${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.ARTIFACT_REGISTRY_REPO }}/${{ env.IMAGE_NAME }}:latest

      - name: Deploy to Cloud Run
        id: deploy
        uses: google-github-actions/deploy-cloudrun@v2
        with:
          service: ${{ env.SERVICE_NAME }}
          region: ${{ env.GAR_LOCATION }}
          image: ${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.ARTIFACT_REGISTRY_REPO }}/${{ env.IMAGE_NAME }}:${{ github.sha }}
          platform: managed
          allow_unauthenticated: true
          # Add any other Cloud Run specific flags here, for example:
          # memory: "512Mi"
          # cpu: "1"
          # timeout: "300s"
          # concurrency: "80"
          # min-instances: "0"
          # max-instances: "2"
          # env_vars: |
          #   NODE_ENV=production
          #   YOUR_OTHER_VARIABLE=${{ secrets.YOUR_OTHER_SECRET }}

      - name: Show Deployed URL Test 
        run: echo "Deployment URL will appear here." 

# How to set up GitHub Secrets:
# 1. GCP_PROJECT_ID: Your Google Cloud Project ID (e.g., coffeespot-booking).
# 2. GCP_WORKLOAD_IDENTITY_PROVIDER: The full identifier of your Workload Identity Provider.
#    Format: projects/PROJECT_NUMBER/locations/global/workloadIdentityPools/POOL_ID/providers/PROVIDER_ID
#    (e.g., projects/182184842256/locations/global/workloadIdentityPools/github-actions-pool/providers/YOUR_OIDC_PROVIDER_ID)
# 3. GCP_SERVICE_ACCOUNT: The email address of the Google Cloud Service Account that GitHub Actions will impersonate.
#    This service account needs roles like:
#    - Artifact Registry Writer (roles/artifactregistry.writer) - to push images
#    - Cloud Run Developer (roles/run.developer) - to deploy services
#    - Service Account User (roles/iam.serviceAccountUser) - to impersonate this service account
#
# Before running:
# - Ensure Artifact Registry API is enabled in your GCP project (e.g., coffeespot-booking).
# - Ensure Cloud Run API is enabled in your GCP project (e.g., coffeespot-booking).
# - Create an Artifact Registry repository named as per ARTIFACT_REGISTRY_REPO (e.g., coffeespot-booking-repo) in the specified GAR_LOCATION (us-central1).
# - Configure Workload Identity Federation between GitHub Actions and your GCP project (project 182184842256 for the WIF pool).
# - Ensure the service account has the "Workload Identity User" role for the principalSet from your WIF provider.
